version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pushkin
      POSTGRES_PASSWORD: dantes1837
      POSTGRES_DB: service
  backend:
    build:
      context: .
    expose:
      - 8080
    command: bash -c "
      ./wait-for-postgre.sh db
      && python /service/manage.py makemigrations users
      && python /service/manage.py makemigrations todo_app
      && python /service/manage.py migrate
      && cd /service
      && gunicorn service.wsgi -b 0.0.0.0:8080
      "
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx
